//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppUtil.java
//

#include "AppUtil.h"
#include "J2ObjC_source.h"

@implementation AppBaseAppUtil

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AppBaseAppUtil_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jboolean)isEmptyWithNSString:(NSString *)text {
  return AppBaseAppUtil_isEmptyWithNSString_(text);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(isEmptyWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "isEmpty", "LNSString;" };
  static const J2ObjcClassInfo _AppBaseAppUtil = { "AppUtil", "br.com.mobilemind.j2objc.util", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_AppBaseAppUtil;
}

@end

void AppBaseAppUtil_init(AppBaseAppUtil *self) {
  NSObject_init(self);
}

AppBaseAppUtil *new_AppBaseAppUtil_init() {
  J2OBJC_NEW_IMPL(AppBaseAppUtil, init)
}

AppBaseAppUtil *create_AppBaseAppUtil_init() {
  J2OBJC_CREATE_IMPL(AppBaseAppUtil, init)
}

jboolean AppBaseAppUtil_isEmptyWithNSString_(NSString *text) {
  AppBaseAppUtil_initialize();
  return text == nil || [((NSString *) nil_chk([text java_trim])) java_length] == 0;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AppBaseAppUtil)
