//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JavaBridging.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaBridging")
#ifdef RESTRICT_JavaBridging
#define INCLUDE_ALL_JavaBridging 0
#else
#define INCLUDE_ALL_JavaBridging 1
#endif
#undef RESTRICT_JavaBridging

#if !defined (AppJavaBridging_) && (INCLUDE_ALL_JavaBridging || defined(INCLUDE_AppJavaBridging))
#define AppJavaBridging_

@interface AppJavaBridging : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AppJavaBridging)

FOUNDATION_EXPORT void AppJavaBridging_init(AppJavaBridging *self);

FOUNDATION_EXPORT AppJavaBridging *new_AppJavaBridging_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppJavaBridging *create_AppJavaBridging_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppJavaBridging)

@compatibility_alias BrComMobilemindAppJavaBridging AppJavaBridging;

#endif

#pragma pop_macro("INCLUDE_ALL_JavaBridging")
