//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RestResult.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RestResult")
#ifdef RESTRICT_RestResult
#define INCLUDE_ALL_RestResult 0
#else
#define INCLUDE_ALL_RestResult 1
#endif
#undef RESTRICT_RestResult

#if !defined (AppBaseRestResult_) && (INCLUDE_ALL_RestResult || defined(INCLUDE_AppBaseRestResult))
#define AppBaseRestResult_

@protocol JavaUtilList;

@interface AppBaseRestResult : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)getMessage;

- (id)getResult;

- (id<JavaUtilList>)getResults;

- (jboolean)isError;

- (void)setErrorWithBoolean:(jboolean)error;

- (void)setMessageWithNSString:(NSString *)message;

- (void)setResultWithId:(id)result;

- (void)setResultsWithJavaUtilList:(id<JavaUtilList>)results;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseRestResult)

FOUNDATION_EXPORT void AppBaseRestResult_init(AppBaseRestResult *self);

FOUNDATION_EXPORT AppBaseRestResult *new_AppBaseRestResult_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestResult *create_AppBaseRestResult_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseRestResult)

@compatibility_alias BrComMobilemindJ2objcRestRestResult AppBaseRestResult;

#endif

#pragma pop_macro("INCLUDE_ALL_RestResult")
