//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SyncStatus.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SyncStatus")
#ifdef RESTRICT_SyncStatus
#define INCLUDE_ALL_SyncStatus 0
#else
#define INCLUDE_ALL_SyncStatus 1
#endif
#undef RESTRICT_SyncStatus

#if !defined (AppBaseSyncStatus_) && (INCLUDE_ALL_SyncStatus || defined(INCLUDE_AppBaseSyncStatus))
#define AppBaseSyncStatus_

@interface AppBaseSyncStatus : NSObject

+ (NSString *)NONE;

+ (void)setNONE:(NSString *)value;

+ (NSString *)CHANGED;

+ (void)setCHANGED:(NSString *)value;

+ (NSString *)DELETED;

+ (void)setDELETED:(NSString *)value;

+ (NSString *)SYNC_OK;

+ (void)setSYNC_OK:(NSString *)value;

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseSyncStatus)

inline NSString *AppBaseSyncStatus_get_NONE(void);
inline NSString *AppBaseSyncStatus_set_NONE(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AppBaseSyncStatus_NONE;
J2OBJC_STATIC_FIELD_OBJ(AppBaseSyncStatus, NONE, NSString *)

inline NSString *AppBaseSyncStatus_get_CHANGED(void);
inline NSString *AppBaseSyncStatus_set_CHANGED(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AppBaseSyncStatus_CHANGED;
J2OBJC_STATIC_FIELD_OBJ(AppBaseSyncStatus, CHANGED, NSString *)

inline NSString *AppBaseSyncStatus_get_DELETED(void);
inline NSString *AppBaseSyncStatus_set_DELETED(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AppBaseSyncStatus_DELETED;
J2OBJC_STATIC_FIELD_OBJ(AppBaseSyncStatus, DELETED, NSString *)

inline NSString *AppBaseSyncStatus_get_SYNC_OK(void);
inline NSString *AppBaseSyncStatus_set_SYNC_OK(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AppBaseSyncStatus_SYNC_OK;
J2OBJC_STATIC_FIELD_OBJ(AppBaseSyncStatus, SYNC_OK, NSString *)

FOUNDATION_EXPORT void AppBaseSyncStatus_init(AppBaseSyncStatus *self);

FOUNDATION_EXPORT AppBaseSyncStatus *new_AppBaseSyncStatus_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseSyncStatus *create_AppBaseSyncStatus_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseSyncStatus)

@compatibility_alias BrComMobilemindJ2objcModelSyncStatus AppBaseSyncStatus;

#endif

#pragma pop_macro("INCLUDE_ALL_SyncStatus")
