//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/UserRepository.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UserRepository")
#ifdef RESTRICT_UserRepository
#define INCLUDE_ALL_UserRepository 0
#else
#define INCLUDE_ALL_UserRepository 1
#endif
#undef RESTRICT_UserRepository

#if !defined (AppUserRepository_) && (INCLUDE_ALL_UserRepository || defined(INCLUDE_AppUserRepository))
#define AppUserRepository_

#define RESTRICT_BaseRepository 1
#define INCLUDE_AppBaseRepository 1
#include "BaseRepository.h"

@class AppUser;
@class ComYahooSquidbSqlProperty;
@class ComYahooSquidbSqlTable;
@class IOSClass;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface AppUserRepository : AppBaseRepository

#pragma mark Public

- (instancetype)init;

- (jboolean)exists;

- (id<JavaUtilList>)findAll;

- (AppUser *)findByIdWithLong:(jlong)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithIOSClass:(IOSClass *)arg0
      withComYahooSquidbSqlTable:(ComYahooSquidbSqlTable *)arg1
withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)arg2
   withComYahooSquidbSqlProperty:(ComYahooSquidbSqlProperty *)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AppUserRepository)

FOUNDATION_EXPORT void AppUserRepository_init(AppUserRepository *self);

FOUNDATION_EXPORT AppUserRepository *new_AppUserRepository_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUserRepository *create_AppUserRepository_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppUserRepository)

@compatibility_alias BrComMobilemindAppRepositoryUserRepository AppUserRepository;

#endif

#pragma pop_macro("INCLUDE_ALL_UserRepository")
