# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'j2objcApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for j2objcApp


  #change CursorWindowNative e SQLiteConnectionNative - add sqlite general > Linked framework and libs
  pod 'IQKeyboardManagerSwift', '4.0.10'
  pod 'sqlite3'

  # dependencies shoud be setted at AppShare.podspec and here, because podspec does not
  # accepts local path on dependency, only pod dependency to download
  #pod 'SquiDB', :path => '../../../libs/squidb/ios'
  #pod 'J2ObjCAppBase', :path => '../../../libs/j2objc-app-base/ios'
  #pod 'J2ObjCGson', :path => '../../../libs/j2objc-gson/ios'
  #pod 'J2ObjCUnit', :path => '../../../libs/j2objc-unit/ios'

  pod 'AppShare', :path => '../../share/ios'

  post_install do |installer_representation|

      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
              config.build_settings['VALID_ARCHITECTURES'] = 'arm64 armv7 armv7s'
              config.build_settings['J2OBJC_HOME'] = '/opt/j2objc'


          end
      end
  end

end
