//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppDatabase.java
//

#ifndef AppDatabase_H
#define AppDatabase_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "SquidDatabase.h"

@class IOSObjectArray;
@protocol ComYahooSquidbDataISQLiteDatabase;
@protocol ComYahooSquidbDataISQLiteOpenHelper;

@interface SGDBAppDatabase : ComYahooSquidbDataSquidDatabase

#pragma mark Public

+ (SGDBAppDatabase *)getInstance;

- (NSString *)getName;

#pragma mark Protected

- (id<ComYahooSquidbDataISQLiteOpenHelper>)createOpenHelperWithNSString:(NSString *)databaseName
                 withComYahooSquidbDataSquidDatabase_OpenHelperDelegate:(ComYahooSquidbDataSquidDatabase_OpenHelperDelegate *)delegate
                                                                withInt:(jint)version_;

- (IOSObjectArray *)getTables;

- (jint)getVersion;

- (jboolean)onUpgradeWithComYahooSquidbDataISQLiteDatabase:(id<ComYahooSquidbDataISQLiteDatabase>)db
                                                   withInt:(jint)oldVersion
                                                   withInt:(jint)newVersion;

@end

J2OBJC_EMPTY_STATIC_INIT(SGDBAppDatabase)

FOUNDATION_EXPORT SGDBAppDatabase *SGDBAppDatabase_getInstance(void);

J2OBJC_TYPE_LITERAL_HEADER(SGDBAppDatabase)

@compatibility_alias BrComMobilemindAppDatabaseAppDatabase SGDBAppDatabase;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // AppDatabase_H
