//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppShareConstants.java
//

#include "AppShareConstants.h"
#include "J2ObjC_source.h"

NSString *AppAppShareConstants_SERVER_END_POINT = @"http://10.0.0.103:3000/api";

@implementation AppAppShareConstants

+ (NSString *)SERVER_END_POINT {
  return AppAppShareConstants_SERVER_END_POINT;
}

+ (void)setSERVER_END_POINT:(NSString *)value {
  AppAppShareConstants_SERVER_END_POINT = value;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AppAppShareConstants_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SERVER_END_POINT", "LNSString;", .constantValue.asLong = 0, 0x9, -1, 0, -1, -1 },
  };
  static const void *ptrTable[] = { &AppAppShareConstants_SERVER_END_POINT };
  static const J2ObjcClassInfo _AppAppShareConstants = { "AppShareConstants", "br.com.mobilemind.app.util", ptrTable, methods, fields, 7, 0x1, 1, 1, -1, -1, -1, -1, -1 };
  return &_AppAppShareConstants;
}

@end

void AppAppShareConstants_init(AppAppShareConstants *self) {
  NSObject_init(self);
}

AppAppShareConstants *new_AppAppShareConstants_init() {
  J2OBJC_NEW_IMPL(AppAppShareConstants, init)
}

AppAppShareConstants *create_AppAppShareConstants_init() {
  J2OBJC_CREATE_IMPL(AppAppShareConstants, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AppAppShareConstants)
