//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppShareConstants.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppShareConstants")
#ifdef RESTRICT_AppShareConstants
#define INCLUDE_ALL_AppShareConstants 0
#else
#define INCLUDE_ALL_AppShareConstants 1
#endif
#undef RESTRICT_AppShareConstants

#if !defined (AppAppShareConstants_) && (INCLUDE_ALL_AppShareConstants || defined(INCLUDE_AppAppShareConstants))
#define AppAppShareConstants_

@interface AppAppShareConstants : NSObject

+ (NSString *)SERVER_END_POINT;

+ (void)setSERVER_END_POINT:(NSString *)value;

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AppAppShareConstants)

inline NSString *AppAppShareConstants_get_SERVER_END_POINT(void);
inline NSString *AppAppShareConstants_set_SERVER_END_POINT(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AppAppShareConstants_SERVER_END_POINT;
J2OBJC_STATIC_FIELD_OBJ(AppAppShareConstants, SERVER_END_POINT, NSString *)

FOUNDATION_EXPORT void AppAppShareConstants_init(AppAppShareConstants *self);

FOUNDATION_EXPORT AppAppShareConstants *new_AppAppShareConstants_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppAppShareConstants *create_AppAppShareConstants_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppAppShareConstants)

@compatibility_alias BrComMobilemindAppUtilAppShareConstants AppAppShareConstants;

#endif

#pragma pop_macro("INCLUDE_ALL_AppShareConstants")
