//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppUtil.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppUtil")
#ifdef RESTRICT_AppUtil
#define INCLUDE_ALL_AppUtil 0
#else
#define INCLUDE_ALL_AppUtil 1
#endif
#undef RESTRICT_AppUtil

#if !defined (AppBaseAppUtil_) && (INCLUDE_ALL_AppUtil || defined(INCLUDE_AppBaseAppUtil))
#define AppBaseAppUtil_

@interface AppBaseAppUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)isEmptyWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseAppUtil)

FOUNDATION_EXPORT void AppBaseAppUtil_init(AppBaseAppUtil *self);

FOUNDATION_EXPORT AppBaseAppUtil *new_AppBaseAppUtil_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseAppUtil *create_AppBaseAppUtil_init(void);

FOUNDATION_EXPORT jboolean AppBaseAppUtil_isEmptyWithNSString_(NSString *text);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseAppUtil)

@compatibility_alias BrComMobilemindJ2objcUtilAppUtil AppBaseAppUtil;

#endif

#pragma pop_macro("INCLUDE_ALL_AppUtil")
