//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/AppUtil.java
//

#ifndef AppUtil_H
#define AppUtil_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class IOSCharArray;

@interface AppBaseAppUtil : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (NSString *)capitalizeStringWithNSString:(NSString *)string
                             withCharArray:(IOSCharArray *)charList;

+ (jdouble)decimalFormatWithDouble:(jdouble)value;

+ (NSString *)filterNumberWithNSString:(NSString *)str;

+ (jdouble)formatMoneyWithDouble:(jdouble)value;

+ (NSString *)formatMoneyStrWithDouble:(jdouble)value;

+ (jboolean)isNullOrEmptyWithNSString:(NSString *)text;

+ (jdouble)parseMoneyWithNSString:(NSString *)value;

+ (NSString *)trimWithNSString:(NSString *)text;

@end

J2OBJC_STATIC_INIT(AppBaseAppUtil)

FOUNDATION_EXPORT void AppBaseAppUtil_init(AppBaseAppUtil *self);

FOUNDATION_EXPORT AppBaseAppUtil *new_AppBaseAppUtil_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseAppUtil *create_AppBaseAppUtil_init(void);

FOUNDATION_EXPORT jboolean AppBaseAppUtil_isNullOrEmptyWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseAppUtil_trimWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseAppUtil_filterNumberWithNSString_(NSString *str);

FOUNDATION_EXPORT jdouble AppBaseAppUtil_decimalFormatWithDouble_(jdouble value);

FOUNDATION_EXPORT jdouble AppBaseAppUtil_formatMoneyWithDouble_(jdouble value);

FOUNDATION_EXPORT NSString *AppBaseAppUtil_formatMoneyStrWithDouble_(jdouble value);

FOUNDATION_EXPORT jdouble AppBaseAppUtil_parseMoneyWithNSString_(NSString *value);

FOUNDATION_EXPORT NSString *AppBaseAppUtil_capitalizeStringWithNSString_withCharArray_(NSString *string, IOSCharArray *charList);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseAppUtil)

@compatibility_alias BrComMobilemindJ2objcUtilAppUtil AppBaseAppUtil;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // AppUtil_H
