//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/BaseRepository.java
//

#ifndef BaseRepository_H
#define BaseRepository_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class ComYahooSquidbDataTableModel;
@class ComYahooSquidbSqlProperty;
@class ComYahooSquidbSqlQuery;
@class ComYahooSquidbSqlTable;
@class IOSClass;
@class IOSObjectArray;
@class SGDBAppDatabase;
@protocol JavaUtilList;

@interface AppBaseRepository : NSObject {
 @public
  SGDBAppDatabase *database_;
}

#pragma mark Public

- (jboolean)delete__WithComYahooSquidbDataTableModel:(ComYahooSquidbDataTableModel *)entity;

- (jint)deleteAll;

- (id<JavaUtilList>)findAll;

- (ComYahooSquidbDataTableModel *)findByIdWithLong:(jlong)id_;

- (ComYahooSquidbSqlQuery *)query;

- (void)saveWithComYahooSquidbDataTableModel:(ComYahooSquidbDataTableModel *)entity;

#pragma mark Protected

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)clazz
                withComYahooSquidbSqlTable:(ComYahooSquidbSqlTable *)table
        withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)properties
             withComYahooSquidbSqlProperty:(ComYahooSquidbSqlProperty *)idProperty;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseRepository)

J2OBJC_FIELD_SETTER(AppBaseRepository, database_, SGDBAppDatabase *)

FOUNDATION_EXPORT void AppBaseRepository_initWithIOSClass_withComYahooSquidbSqlTable_withComYahooSquidbSqlPropertyArray_withComYahooSquidbSqlProperty_(AppBaseRepository *self, IOSClass *clazz, ComYahooSquidbSqlTable *table, IOSObjectArray *properties, ComYahooSquidbSqlProperty *idProperty);

FOUNDATION_EXPORT AppBaseRepository *new_AppBaseRepository_initWithIOSClass_withComYahooSquidbSqlTable_withComYahooSquidbSqlPropertyArray_withComYahooSquidbSqlProperty_(IOSClass *clazz, ComYahooSquidbSqlTable *table, IOSObjectArray *properties, ComYahooSquidbSqlProperty *idProperty) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRepository *create_AppBaseRepository_initWithIOSClass_withComYahooSquidbSqlTable_withComYahooSquidbSqlPropertyArray_withComYahooSquidbSqlProperty_(IOSClass *clazz, ComYahooSquidbSqlTable *table, IOSObjectArray *properties, ComYahooSquidbSqlProperty *idProperty);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseRepository)

@compatibility_alias BrComMobilemindAppRepositoryBaseRepository AppBaseRepository;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // BaseRepository_H
