//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CardSupport.java
//

#include "AppUtil.h"
#include "CardSupport.h"
#include "J2ObjC_source.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

@interface AppBaseCardSupport_1 : JavaUtilHashMap

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseCardSupport_1)

__attribute__((unused)) static void AppBaseCardSupport_1_init(AppBaseCardSupport_1 *self);

__attribute__((unused)) static AppBaseCardSupport_1 *new_AppBaseCardSupport_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static AppBaseCardSupport_1 *create_AppBaseCardSupport_1_init(void);

@implementation AppBaseCardSupport

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AppBaseCardSupport_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (NSString *)getBandeiraWithNSString:(NSString *)numero {
  return AppBaseCardSupport_getBandeiraWithNSString_(numero);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getBandeiraWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getBandeira", "LNSString;" };
  static const J2ObjcClassInfo _AppBaseCardSupport = { "CardSupport", "br.com.mobilemind.j2objc.payments", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_AppBaseCardSupport;
}

@end

void AppBaseCardSupport_init(AppBaseCardSupport *self) {
  NSObject_init(self);
}

AppBaseCardSupport *new_AppBaseCardSupport_init() {
  J2OBJC_NEW_IMPL(AppBaseCardSupport, init)
}

AppBaseCardSupport *create_AppBaseCardSupport_init() {
  J2OBJC_CREATE_IMPL(AppBaseCardSupport, init)
}

NSString *AppBaseCardSupport_getBandeiraWithNSString_(NSString *numero) {
  AppBaseCardSupport_initialize();
  if (numero == nil) return nil;
  numero = AppBaseAppUtil_filterNumberWithNSString_(numero);
  id<JavaUtilMap> values = new_AppBaseCardSupport_1_init();
  for (id<JavaUtilMap_Entry> __strong entry_ in nil_chk([values entrySet])) {
    if ([((NSString *) nil_chk(numero)) java_matches:[((id<JavaUtilMap_Entry>) nil_chk(entry_)) getValue]]) {
      return [entry_ getKey];
    }
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AppBaseCardSupport)

J2OBJC_NAME_MAPPING(AppBaseCardSupport, "br.com.mobilemind.j2objc.payments", "AppBase")

@implementation AppBaseCardSupport_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AppBaseCardSupport_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LAppBaseCardSupport;", "getBandeiraWithNSString:" };
  static const J2ObjcClassInfo _AppBaseCardSupport_1 = { "", "br.com.mobilemind.j2objc.payments", ptrTable, methods, NULL, 7, 0x8018, 1, 0, 0, -1, 1, -1, -1 };
  return &_AppBaseCardSupport_1;
}

@end

void AppBaseCardSupport_1_init(AppBaseCardSupport_1 *self) {
  JavaUtilHashMap_init(self);
  {
    (void) [self putWithId:@"VISA" withId:@"^4[0-9]{12}(?:[0-9]{3})"];
    (void) [self putWithId:@"MASTERCARD" withId:@"^5[1-5][0-9]{14}"];
    (void) [self putWithId:@"AMEX" withId:@"^3[47][0-9]{13}"];
    (void) [self putWithId:@"JCB" withId:@"^(?:2131|1800|35\\d{3})\\d{11}"];
    (void) [self putWithId:@"DINERS" withId:@"^3(?:0[0-5]|[68][0-9])[0-9]{11}"];
    (void) [self putWithId:@"DISCOVER" withId:@"^6(?:011|5[0-9]{2})[0-9]{12}"];
    (void) [self putWithId:@"ELO" withId:@"^((((636368)|(438935)|(504175)|(451416)|(636297))\\d{0,10})|((5067)|(4576)|(4011))\\d{0,12})$"];
    (void) [self putWithId:@"HIPERCARD" withId:@"^(606282\\d{10}(\\d{3})?)|(3841\\d{15})$"];
  }
}

AppBaseCardSupport_1 *new_AppBaseCardSupport_1_init() {
  J2OBJC_NEW_IMPL(AppBaseCardSupport_1, init)
}

AppBaseCardSupport_1 *create_AppBaseCardSupport_1_init() {
  J2OBJC_CREATE_IMPL(AppBaseCardSupport_1, init)
}
