//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CardSupport.java
//

#ifndef CardSupport_H
#define CardSupport_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@interface AppBaseCardSupport : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (NSString *)getBandeiraWithNSString:(NSString *)numero;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseCardSupport)

FOUNDATION_EXPORT void AppBaseCardSupport_init(AppBaseCardSupport *self);

FOUNDATION_EXPORT AppBaseCardSupport *new_AppBaseCardSupport_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseCardSupport *create_AppBaseCardSupport_init(void);

FOUNDATION_EXPORT NSString *AppBaseCardSupport_getBandeiraWithNSString_(NSString *numero);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseCardSupport)

@compatibility_alias BrComMobilemindJ2objcPaymentsCardSupport AppBaseCardSupport;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // CardSupport_H
