//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/HttpException.java
//

#ifndef HttpException_H
#define HttpException_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

@class JavaLangException;
@class JavaLangThrowable;

@interface BrComMobilemindJ2objcHttpHttpException : JavaLangRuntimeException

#pragma mark Public

- (instancetype __nonnull)initWithInt:(jint)httpStatus;

- (instancetype __nonnull)initWithInt:(jint)httpStatus
                withJavaLangException:(JavaLangException *)e;

- (instancetype __nonnull)initWithInt:(jint)httpStatus
                         withNSString:(NSString *)message;

- (instancetype __nonnull)initWithInt:(jint)httpStatus
                         withNSString:(NSString *)message
                withJavaLangException:(JavaLangException *)e;

- (jint)getHttpSatatus;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(BrComMobilemindJ2objcHttpHttpException)

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_withJavaLangException_(BrComMobilemindJ2objcHttpHttpException *self, jint httpStatus, NSString *message, JavaLangException *e);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *new_BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_withJavaLangException_(jint httpStatus, NSString *message, JavaLangException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *create_BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_withJavaLangException_(jint httpStatus, NSString *message, JavaLangException *e);

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpHttpException_initWithInt_withJavaLangException_(BrComMobilemindJ2objcHttpHttpException *self, jint httpStatus, JavaLangException *e);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *new_BrComMobilemindJ2objcHttpHttpException_initWithInt_withJavaLangException_(jint httpStatus, JavaLangException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *create_BrComMobilemindJ2objcHttpHttpException_initWithInt_withJavaLangException_(jint httpStatus, JavaLangException *e);

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_(BrComMobilemindJ2objcHttpHttpException *self, jint httpStatus, NSString *message);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *new_BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_(jint httpStatus, NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *create_BrComMobilemindJ2objcHttpHttpException_initWithInt_withNSString_(jint httpStatus, NSString *message);

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpHttpException_initWithInt_(BrComMobilemindJ2objcHttpHttpException *self, jint httpStatus);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *new_BrComMobilemindJ2objcHttpHttpException_initWithInt_(jint httpStatus) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpHttpException *create_BrComMobilemindJ2objcHttpHttpException_initWithInt_(jint httpStatus);

J2OBJC_TYPE_LITERAL_HEADER(BrComMobilemindJ2objcHttpHttpException)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // HttpException_H
