//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/IOSOpenHelperCreator.java
//

#ifndef IOSOpenHelperCreator_H
#define IOSOpenHelperCreator_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "OpenHelperCreator.h"

@class ComYahooSquidbDataSquidDatabase_OpenHelperDelegate;
@protocol ComYahooSquidbDataISQLiteOpenHelper;

@interface SGDBIOSOpenHelperCreator : SGDBOpenHelperCreator

#pragma mark Public

- (instancetype __nonnull)init;

#pragma mark Protected

- (id<ComYahooSquidbDataISQLiteOpenHelper>)createOpenHelperWithNSString:(NSString *)databaseName
                 withComYahooSquidbDataSquidDatabase_OpenHelperDelegate:(ComYahooSquidbDataSquidDatabase_OpenHelperDelegate *)delegate
                                                                withInt:(jint)version_;

@end

J2OBJC_EMPTY_STATIC_INIT(SGDBIOSOpenHelperCreator)

FOUNDATION_EXPORT void SGDBIOSOpenHelperCreator_init(SGDBIOSOpenHelperCreator *self);

FOUNDATION_EXPORT SGDBIOSOpenHelperCreator *new_SGDBIOSOpenHelperCreator_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SGDBIOSOpenHelperCreator *create_SGDBIOSOpenHelperCreator_init(void);

J2OBJC_TYPE_LITERAL_HEADER(SGDBIOSOpenHelperCreator)

@compatibility_alias BrComMobilemindAppIosIOSOpenHelperCreator SGDBIOSOpenHelperCreator;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // IOSOpenHelperCreator_H
