//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JavaBridging.java
//

#ifndef JavaBridging_H
#define JavaBridging_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@interface AppJavaBridging : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AppJavaBridging)

FOUNDATION_EXPORT void AppJavaBridging_init(AppJavaBridging *self);

FOUNDATION_EXPORT AppJavaBridging *new_AppJavaBridging_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppJavaBridging *create_AppJavaBridging_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppJavaBridging)

@compatibility_alias BrComMobilemindAppJavaBridging AppJavaBridging;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JavaBridging_H
