//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/NumberMask.java
//

#ifndef NumberMask_H
#define NumberMask_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@interface AppBaseNumberMask : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (NSString *)applyWithNSString:(NSString *)text
                   withNSString:(NSString *)pattern;

+ (NSString *)applyReverseWithNSString:(NSString *)text
                          withNSString:(NSString *)pattern;

+ (NSString *)cepWithNSString:(NSString *)text;

+ (NSString *)documentoWithNSString:(NSString *)text;

+ (NSString *)telefoneWithNSString:(NSString *)text;

+ (NSString *)unmaskWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseNumberMask)

FOUNDATION_EXPORT void AppBaseNumberMask_init(AppBaseNumberMask *self);

FOUNDATION_EXPORT AppBaseNumberMask *new_AppBaseNumberMask_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseNumberMask *create_AppBaseNumberMask_init(void);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_applyWithNSString_withNSString_(NSString *text, NSString *pattern);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_applyReverseWithNSString_withNSString_(NSString *text, NSString *pattern);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_unmaskWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_documentoWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_cepWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_telefoneWithNSString_(NSString *text);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseNumberMask)

@compatibility_alias BrComMobilemindJ2objcUtilNumberMask AppBaseNumberMask;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // NumberMask_H
