//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OpenHelperCreator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OpenHelperCreator")
#ifdef RESTRICT_OpenHelperCreator
#define INCLUDE_ALL_OpenHelperCreator 0
#else
#define INCLUDE_ALL_OpenHelperCreator 1
#endif
#undef RESTRICT_OpenHelperCreator

#if !defined (SGDBOpenHelperCreator_) && (INCLUDE_ALL_OpenHelperCreator || defined(INCLUDE_SGDBOpenHelperCreator))
#define SGDBOpenHelperCreator_

@class ComYahooSquidbDataSquidDatabase_OpenHelperDelegate;
@protocol ComYahooSquidbDataISQLiteOpenHelper;

@interface SGDBOpenHelperCreator : NSObject

#pragma mark Public

- (instancetype)init;

+ (SGDBOpenHelperCreator *)getCreator;

+ (void)setCreatorWithSGDBOpenHelperCreator:(SGDBOpenHelperCreator *)creator;

#pragma mark Protected

- (id<ComYahooSquidbDataISQLiteOpenHelper>)createOpenHelperWithNSString:(NSString *)databaseName
                 withComYahooSquidbDataSquidDatabase_OpenHelperDelegate:(ComYahooSquidbDataSquidDatabase_OpenHelperDelegate *)delegate
                                                                withInt:(jint)version_;

@end

J2OBJC_EMPTY_STATIC_INIT(SGDBOpenHelperCreator)

FOUNDATION_EXPORT void SGDBOpenHelperCreator_init(SGDBOpenHelperCreator *self);

FOUNDATION_EXPORT SGDBOpenHelperCreator *SGDBOpenHelperCreator_getCreator(void);

FOUNDATION_EXPORT void SGDBOpenHelperCreator_setCreatorWithSGDBOpenHelperCreator_(SGDBOpenHelperCreator *creator);

J2OBJC_TYPE_LITERAL_HEADER(SGDBOpenHelperCreator)

@compatibility_alias BrComMobilemindAppDatabaseOpenHelperCreator SGDBOpenHelperCreator;

#endif

#pragma pop_macro("INCLUDE_ALL_OpenHelperCreator")
