//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Preferences.java
//

#include "J2ObjC_source.h"
#include "Preferences.h"

@interface AppBasePreferences : NSObject

@end

@implementation AppBasePreferences

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 4, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 5, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 7, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 8, 9, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 10, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 11, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(hasKeyWithNSString:);
  methods[1].selector = @selector(setStringWithNSString:withNSString:);
  methods[2].selector = @selector(getStringWithNSString:);
  methods[3].selector = @selector(setIntWithNSString:withInt:);
  methods[4].selector = @selector(getIntWithNSString:);
  methods[5].selector = @selector(setBoolWithNSString:withBoolean:);
  methods[6].selector = @selector(getBoolWithNSString:);
  methods[7].selector = @selector(removeWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "hasKey", "LNSString;", "setString", "LNSString;LNSString;", "getString", "setInt", "LNSString;I", "getInt", "setBool", "LNSString;Z", "getBool", "remove" };
  static const J2ObjcClassInfo _AppBasePreferences = { "Preferences", "br.com.mobilemind.j2objc.shared", ptrTable, methods, NULL, 7, 0x609, 8, 0, -1, -1, -1, -1, -1 };
  return &_AppBasePreferences;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AppBasePreferences)
