//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/PreferencesImpl.java
//

#ifndef PreferencesImpl_H
#define PreferencesImpl_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "Preferences.h"

@protocol JavaUtilList;

@interface IOSPreferencesImpl : NSObject < AppBasePreferences >

#pragma mark Public

- (instancetype __nonnull)init;

- (id<JavaUtilList>)allKeys;

- (void)clear;

- (jboolean)getBoolWithNSString:(NSString *)keyName;

- (jint)getIntWithNSString:(NSString *)keyName;

- (NSString *)getStringWithNSString:(NSString *)keyName;

- (jboolean)hasKeyWithNSString:(NSString *)keyName;

- (void)removeWithNSString:(NSString *)keyName;

- (jboolean)setBoolWithNSString:(NSString *)keyName
                    withBoolean:(jboolean)value;

- (jboolean)setIntWithNSString:(NSString *)keyName
                       withInt:(jint)value;

- (jboolean)setStringWithNSString:(NSString *)keyName
                     withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(IOSPreferencesImpl)

FOUNDATION_EXPORT void IOSPreferencesImpl_init(IOSPreferencesImpl *self);

FOUNDATION_EXPORT IOSPreferencesImpl *new_IOSPreferencesImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IOSPreferencesImpl *create_IOSPreferencesImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(IOSPreferencesImpl)

@compatibility_alias BrComMobilemindJ2objcSharedIosPreferencesImpl IOSPreferencesImpl;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // PreferencesImpl_H
