//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Preferences.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Preferences")
#ifdef RESTRICT_Preferences
#define INCLUDE_ALL_Preferences 0
#else
#define INCLUDE_ALL_Preferences 1
#endif
#undef RESTRICT_Preferences

#if !defined (AppBasePreferences_) && (INCLUDE_ALL_Preferences || defined(INCLUDE_AppBasePreferences))
#define AppBasePreferences_

@protocol AppBasePreferences < JavaObject >

- (jboolean)hasKeyWithNSString:(NSString *)keyName;

- (jboolean)setStringWithNSString:(NSString *)keyName
                     withNSString:(NSString *)value;

- (NSString *)getStringWithNSString:(NSString *)keyName;

- (jboolean)setIntWithNSString:(NSString *)keyName
                       withInt:(jint)value;

- (jint)getIntWithNSString:(NSString *)keyName;

- (jboolean)setBoolWithNSString:(NSString *)keyName
                    withBoolean:(jboolean)value;

- (jboolean)getBoolWithNSString:(NSString *)keyName;

- (void)removeWithNSString:(NSString *)keyName;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBasePreferences)

J2OBJC_TYPE_LITERAL_HEADER(AppBasePreferences)

#define BrComMobilemindJ2objcSharedPreferences AppBasePreferences

#endif

#pragma pop_macro("INCLUDE_ALL_Preferences")
