//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/PreferencesImpl.java
//

#include "J2ObjC_source.h"
#include "PreferencesImpl.h"

@implementation IOSPreferencesImpl

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  IOSPreferencesImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jboolean)hasKeyWithNSString:(NSString *)keyName {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  return [preferences objectForKey:keyName];
}

- (jboolean)setStringWithNSString:(NSString *)keyName
                     withNSString:(NSString *)value {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  [preferences setValue:value forKey:keyName];
  return [preferences synchronize];
}

- (NSString *)getStringWithNSString:(NSString *)keyName {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  if ([preferences objectForKey:keyName] != nil){
    return [preferences stringForKey:keyName];
  }
  return nil;
}

- (jboolean)setIntWithNSString:(NSString *)keyName
                       withInt:(jint)value {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  [preferences setInteger:value forKey:keyName];
  return [preferences synchronize];
}

- (jint)getIntWithNSString:(NSString *)keyName {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  if ([preferences objectForKey:keyName] != nil){
    return [preferences integerForKey:keyName];
  }
  return -1;
}

- (jboolean)setBoolWithNSString:(NSString *)keyName
                    withBoolean:(jboolean)value {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  [preferences setBool:value forKey:keyName];
  return [preferences synchronize];
}

- (jboolean)getBoolWithNSString:(NSString *)keyName {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  if ([preferences objectForKey:keyName] != nil){
    return [preferences boolForKey:keyName];
  }
  return false;
}

- (void)removeWithNSString:(NSString *)keyName {
  NSUserDefaults *preferences = [NSUserDefaults standardUserDefaults];
  [preferences removeObjectForKey: keyName];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 2, 3, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x101, 4, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 5, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x101, 7, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 8, 9, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 10, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 11, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(hasKeyWithNSString:);
  methods[2].selector = @selector(setStringWithNSString:withNSString:);
  methods[3].selector = @selector(getStringWithNSString:);
  methods[4].selector = @selector(setIntWithNSString:withInt:);
  methods[5].selector = @selector(getIntWithNSString:);
  methods[6].selector = @selector(setBoolWithNSString:withBoolean:);
  methods[7].selector = @selector(getBoolWithNSString:);
  methods[8].selector = @selector(removeWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "hasKey", "LNSString;", "setString", "LNSString;LNSString;", "getString", "setInt", "LNSString;I", "getInt", "setBool", "LNSString;Z", "getBool", "remove" };
  static const J2ObjcClassInfo _IOSPreferencesImpl = { "PreferencesImpl", "br.com.mobilemind.j2objc.shared.ios", ptrTable, methods, NULL, 7, 0x1, 9, 0, -1, -1, -1, -1, -1 };
  return &_IOSPreferencesImpl;
}

@end

void IOSPreferencesImpl_init(IOSPreferencesImpl *self) {
  NSObject_init(self);
}

IOSPreferencesImpl *new_IOSPreferencesImpl_init() {
  J2OBJC_NEW_IMPL(IOSPreferencesImpl, init)
}

IOSPreferencesImpl *create_IOSPreferencesImpl_init() {
  J2OBJC_CREATE_IMPL(IOSPreferencesImpl, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IOSPreferencesImpl)
