//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/PreferencesImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PreferencesImpl")
#ifdef RESTRICT_PreferencesImpl
#define INCLUDE_ALL_PreferencesImpl 0
#else
#define INCLUDE_ALL_PreferencesImpl 1
#endif
#undef RESTRICT_PreferencesImpl

#if !defined (IOSPreferencesImpl_) && (INCLUDE_ALL_PreferencesImpl || defined(INCLUDE_IOSPreferencesImpl))
#define IOSPreferencesImpl_

#define RESTRICT_Preferences 1
#define INCLUDE_AppBasePreferences 1
#include "Preferences.h"

@interface IOSPreferencesImpl : NSObject < AppBasePreferences >

#pragma mark Public

- (instancetype)init;

- (jboolean)getBoolWithNSString:(NSString *)keyName;

- (jint)getIntWithNSString:(NSString *)keyName;

- (NSString *)getStringWithNSString:(NSString *)keyName;

- (jboolean)hasKeyWithNSString:(NSString *)keyName;

- (void)removeWithNSString:(NSString *)keyName;

- (jboolean)setBoolWithNSString:(NSString *)keyName
                    withBoolean:(jboolean)value;

- (jboolean)setIntWithNSString:(NSString *)keyName
                       withInt:(jint)value;

- (jboolean)setStringWithNSString:(NSString *)keyName
                     withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(IOSPreferencesImpl)

FOUNDATION_EXPORT void IOSPreferencesImpl_init(IOSPreferencesImpl *self);

FOUNDATION_EXPORT IOSPreferencesImpl *new_IOSPreferencesImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IOSPreferencesImpl *create_IOSPreferencesImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(IOSPreferencesImpl)

@compatibility_alias BrComMobilemindJ2objcSharedIosPreferencesImpl IOSPreferencesImpl;

#endif

#pragma pop_macro("INCLUDE_ALL_PreferencesImpl")
