//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Response.java
//

#ifndef Response_H
#define Response_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class BrComMobilemindJ2objcHttpTransformer;
@class JavaIoInputStream;
@protocol JavaUtilMap;

@interface BrComMobilemindJ2objcHttpResponse : NSObject
@property (readonly, class) jint HTTP_STATUS_OK NS_SWIFT_NAME(HTTP_STATUS_OK);

+ (jint)HTTP_STATUS_OK;

#pragma mark Public

- (JavaIoInputStream *)getEntity;

- (JavaIoInputStream *)getError;

- (id<JavaUtilMap>)getHeaders;

- (jint)getHttpStatus;

- (jboolean)is200;

- (void)setEntityWithJavaIoInputStream:(JavaIoInputStream *)entity;

- (void)setErrorWithJavaIoInputStream:(JavaIoInputStream *)error;

- (void)setTransformerWithBrComMobilemindJ2objcHttpTransformer:(BrComMobilemindJ2objcHttpTransformer *)transformer;

- (BrComMobilemindJ2objcHttpTransformer *)transformer;

#pragma mark Package-Private

- (instancetype __nonnull)initWithInt:(jint)httpStatus;

- (instancetype __nonnull)initWithInt:(jint)httpStatus
withBrComMobilemindJ2objcHttpTransformer:(BrComMobilemindJ2objcHttpTransformer *)transformer;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(BrComMobilemindJ2objcHttpResponse)

inline jint BrComMobilemindJ2objcHttpResponse_get_HTTP_STATUS_OK(void);
#define BrComMobilemindJ2objcHttpResponse_HTTP_STATUS_OK 200
J2OBJC_STATIC_FIELD_CONSTANT(BrComMobilemindJ2objcHttpResponse, HTTP_STATUS_OK, jint)

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpResponse_initWithInt_(BrComMobilemindJ2objcHttpResponse *self, jint httpStatus);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpResponse *new_BrComMobilemindJ2objcHttpResponse_initWithInt_(jint httpStatus) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpResponse *create_BrComMobilemindJ2objcHttpResponse_initWithInt_(jint httpStatus);

FOUNDATION_EXPORT void BrComMobilemindJ2objcHttpResponse_initWithInt_withBrComMobilemindJ2objcHttpTransformer_(BrComMobilemindJ2objcHttpResponse *self, jint httpStatus, BrComMobilemindJ2objcHttpTransformer *transformer);

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpResponse *new_BrComMobilemindJ2objcHttpResponse_initWithInt_withBrComMobilemindJ2objcHttpTransformer_(jint httpStatus, BrComMobilemindJ2objcHttpTransformer *transformer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcHttpResponse *create_BrComMobilemindJ2objcHttpResponse_initWithInt_withBrComMobilemindJ2objcHttpTransformer_(jint httpStatus, BrComMobilemindJ2objcHttpTransformer *transformer);

J2OBJC_TYPE_LITERAL_HEADER(BrComMobilemindJ2objcHttpResponse)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // Response_H
