//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RestDataConverter.java
//

#ifndef RestDataConverter_H
#define RestDataConverter_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@interface AppBaseRestDataConverter : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (id)fromJsonWithNSString:(NSString *)content;

- (NSString *)toJsonWithId:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseRestDataConverter)

FOUNDATION_EXPORT void AppBaseRestDataConverter_init(AppBaseRestDataConverter *self);

FOUNDATION_EXPORT AppBaseRestDataConverter *new_AppBaseRestDataConverter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestDataConverter *create_AppBaseRestDataConverter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseRestDataConverter)

@compatibility_alias BrComMobilemindJ2objcRestRestDataConverter AppBaseRestDataConverter;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // RestDataConverter_H
