//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RestException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RestException")
#ifdef RESTRICT_RestException
#define INCLUDE_ALL_RestException 0
#else
#define INCLUDE_ALL_RestException 1
#endif
#undef RESTRICT_RestException

#if !defined (AppBaseRestException_) && (INCLUDE_ALL_RestException || defined(INCLUDE_AppBaseRestException))
#define AppBaseRestException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangException;
@class JavaLangThrowable;

@interface AppBaseRestException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaLangException:(JavaLangException *)e;

- (instancetype)initWithInt:(jint)httpStatus;

- (instancetype)initWithInt:(jint)httpStatus
               withNSString:(NSString *)message;

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangException:(JavaLangException *)e;

- (jint)getHttpSatatus;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseRestException)

FOUNDATION_EXPORT void AppBaseRestException_initWithNSString_withJavaLangException_(AppBaseRestException *self, NSString *message, JavaLangException *e);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_initWithNSString_withJavaLangException_(NSString *message, JavaLangException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_initWithNSString_withJavaLangException_(NSString *message, JavaLangException *e);

FOUNDATION_EXPORT void AppBaseRestException_initWithJavaLangException_(AppBaseRestException *self, JavaLangException *e);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_initWithJavaLangException_(JavaLangException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_initWithJavaLangException_(JavaLangException *e);

FOUNDATION_EXPORT void AppBaseRestException_initWithNSString_(AppBaseRestException *self, NSString *message);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_initWithNSString_(NSString *message);

FOUNDATION_EXPORT void AppBaseRestException_init(AppBaseRestException *self);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_init(void);

FOUNDATION_EXPORT void AppBaseRestException_initWithInt_withNSString_(AppBaseRestException *self, jint httpStatus, NSString *message);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_initWithInt_withNSString_(jint httpStatus, NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_initWithInt_withNSString_(jint httpStatus, NSString *message);

FOUNDATION_EXPORT void AppBaseRestException_initWithInt_(AppBaseRestException *self, jint httpStatus);

FOUNDATION_EXPORT AppBaseRestException *new_AppBaseRestException_initWithInt_(jint httpStatus) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestException *create_AppBaseRestException_initWithInt_(jint httpStatus);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseRestException)

@compatibility_alias BrComMobilemindJ2objcRestRestException AppBaseRestException;

#endif

#pragma pop_macro("INCLUDE_ALL_RestException")
