//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RestDataConverter.java
//

#include "J2ObjC_source.h"
#include "RestDataConverter.h"

@implementation AppBaseRestDataConverter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AppBaseRestDataConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id)fromJsonWithNSString:(NSString *)content {
  return nil;
}

- (NSString *)toJsonWithId:(id)obj {
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 0, 1, -1, 2, -1, -1 },
    { NULL, "LNSString;", 0x1, 3, 4, -1, 5, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(fromJsonWithNSString:);
  methods[2].selector = @selector(toJsonWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "fromJson", "LNSString;", "(Ljava/lang/String;)TT;", "toJson", "LNSObject;", "(TT;)Ljava/lang/String;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _AppBaseRestDataConverter = { "RestDataConverter", "br.com.mobilemind.j2objc.rest", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, 6, -1 };
  return &_AppBaseRestDataConverter;
}

@end

void AppBaseRestDataConverter_init(AppBaseRestDataConverter *self) {
  NSObject_init(self);
}

AppBaseRestDataConverter *new_AppBaseRestDataConverter_init() {
  J2OBJC_NEW_IMPL(AppBaseRestDataConverter, init)
}

AppBaseRestDataConverter *create_AppBaseRestDataConverter_init() {
  J2OBJC_CREATE_IMPL(AppBaseRestDataConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AppBaseRestDataConverter)
