//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RestDataConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RestDataConverter")
#ifdef RESTRICT_RestDataConverter
#define INCLUDE_ALL_RestDataConverter 0
#else
#define INCLUDE_ALL_RestDataConverter 1
#endif
#undef RESTRICT_RestDataConverter

#if !defined (AppBaseRestDataConverter_) && (INCLUDE_ALL_RestDataConverter || defined(INCLUDE_AppBaseRestDataConverter))
#define AppBaseRestDataConverter_

@interface AppBaseRestDataConverter : NSObject

#pragma mark Public

- (instancetype)init;

- (id)fromJsonWithNSString:(NSString *)content;

- (NSString *)toJsonWithId:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseRestDataConverter)

FOUNDATION_EXPORT void AppBaseRestDataConverter_init(AppBaseRestDataConverter *self);

FOUNDATION_EXPORT AppBaseRestDataConverter *new_AppBaseRestDataConverter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseRestDataConverter *create_AppBaseRestDataConverter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseRestDataConverter)

@compatibility_alias BrComMobilemindJ2objcRestRestDataConverter AppBaseRestDataConverter;

#endif

#pragma pop_macro("INCLUDE_ALL_RestDataConverter")
