//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/User.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_User")
#ifdef RESTRICT_User
#define INCLUDE_ALL_User 0
#else
#define INCLUDE_ALL_User 1
#endif
#undef RESTRICT_User

#if !defined (AppUser_) && (INCLUDE_ALL_User || defined(INCLUDE_AppUser))
#define AppUser_

#define RESTRICT_TableModel 1
#define INCLUDE_ComYahooSquidbDataTableModel 1
#include "TableModel.h"

@class ComYahooSquidbDataSquidCursor;
@class ComYahooSquidbDataValuesStorage;
@class ComYahooSquidbSqlProperty_LongProperty;
@class ComYahooSquidbSqlProperty_StringProperty;
@class ComYahooSquidbSqlTable;
@class ComYahooSquidbSqlTableModelName;
@class IOSObjectArray;
@protocol JavaUtilMap;

@interface AppUser : ComYahooSquidbDataTableModel

+ (IOSObjectArray *)PROPERTIES;

+ (ComYahooSquidbSqlTable *)TABLE;

+ (ComYahooSquidbSqlTableModelName *)TABLE_MODEL_NAME;

+ (ComYahooSquidbSqlProperty_LongProperty *)ID;

+ (ComYahooSquidbSqlProperty_StringProperty *)NAME;

+ (ComYahooSquidbSqlProperty_StringProperty *)EMAIL;

+ (ComYahooSquidbSqlProperty_StringProperty *)TOKEN;

+ (ComYahooSquidbDataValuesStorage *)defaultValues;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)values;

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)values
 withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)withProperties;

- (instancetype)initWithComYahooSquidbDataSquidCursor:(ComYahooSquidbDataSquidCursor *)cursor;

- (AppUser *)java_clone;

- (ComYahooSquidbDataValuesStorage *)getDefaultValues;

- (NSString *)getEmail;

- (jlong)getId;

- (NSString *)getName;

- (ComYahooSquidbSqlProperty_LongProperty *)getRowIdProperty;

- (NSString *)getToken;

- (AppUser *)setEmailWithNSString:(NSString *)email;

- (AppUser *)setIdWithLong:(jlong)id_;

- (AppUser *)setNameWithNSString:(NSString *)name;

- (AppUser *)setRowIdWithLong:(jlong)rowid;

- (AppUser *)setTokenWithNSString:(NSString *)token;

@end

J2OBJC_STATIC_INIT(AppUser)

inline IOSObjectArray *AppUser_get_PROPERTIES(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *AppUser_PROPERTIES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, PROPERTIES, IOSObjectArray *)

inline ComYahooSquidbSqlTable *AppUser_get_TABLE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlTable *AppUser_TABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, TABLE, ComYahooSquidbSqlTable *)

inline ComYahooSquidbSqlTableModelName *AppUser_get_TABLE_MODEL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlTableModelName *AppUser_TABLE_MODEL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, TABLE_MODEL_NAME, ComYahooSquidbSqlTableModelName *)

inline ComYahooSquidbSqlProperty_LongProperty *AppUser_get_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlProperty_LongProperty *AppUser_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, ID, ComYahooSquidbSqlProperty_LongProperty *)

inline ComYahooSquidbSqlProperty_StringProperty *AppUser_get_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlProperty_StringProperty *AppUser_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, NAME, ComYahooSquidbSqlProperty_StringProperty *)

inline ComYahooSquidbSqlProperty_StringProperty *AppUser_get_EMAIL(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlProperty_StringProperty *AppUser_EMAIL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, EMAIL, ComYahooSquidbSqlProperty_StringProperty *)

inline ComYahooSquidbSqlProperty_StringProperty *AppUser_get_TOKEN(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbSqlProperty_StringProperty *AppUser_TOKEN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, TOKEN, ComYahooSquidbSqlProperty_StringProperty *)

inline ComYahooSquidbDataValuesStorage *AppUser_get_defaultValues(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbDataValuesStorage *AppUser_defaultValues;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUser, defaultValues, ComYahooSquidbDataValuesStorage *)

FOUNDATION_EXPORT void AppUser_init(AppUser *self);

FOUNDATION_EXPORT AppUser *new_AppUser_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUser *create_AppUser_init(void);

FOUNDATION_EXPORT void AppUser_initWithComYahooSquidbDataSquidCursor_(AppUser *self, ComYahooSquidbDataSquidCursor *cursor);

FOUNDATION_EXPORT AppUser *new_AppUser_initWithComYahooSquidbDataSquidCursor_(ComYahooSquidbDataSquidCursor *cursor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUser *create_AppUser_initWithComYahooSquidbDataSquidCursor_(ComYahooSquidbDataSquidCursor *cursor);

FOUNDATION_EXPORT void AppUser_initWithJavaUtilMap_(AppUser *self, id<JavaUtilMap> values);

FOUNDATION_EXPORT AppUser *new_AppUser_initWithJavaUtilMap_(id<JavaUtilMap> values) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUser *create_AppUser_initWithJavaUtilMap_(id<JavaUtilMap> values);

FOUNDATION_EXPORT void AppUser_initWithJavaUtilMap_withComYahooSquidbSqlPropertyArray_(AppUser *self, id<JavaUtilMap> values, IOSObjectArray *withProperties);

FOUNDATION_EXPORT AppUser *new_AppUser_initWithJavaUtilMap_withComYahooSquidbSqlPropertyArray_(id<JavaUtilMap> values, IOSObjectArray *withProperties) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUser *create_AppUser_initWithJavaUtilMap_withComYahooSquidbSqlPropertyArray_(id<JavaUtilMap> values, IOSObjectArray *withProperties);

J2OBJC_TYPE_LITERAL_HEADER(AppUser)

@compatibility_alias BrComMobilemindAppModelUser AppUser;

#endif

#pragma pop_macro("INCLUDE_ALL_User")
