//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/UserController.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UserController")
#ifdef RESTRICT_UserController
#define INCLUDE_ALL_UserController 0
#else
#define INCLUDE_ALL_UserController 1
#endif
#undef RESTRICT_UserController

#if !defined (AppUserController_) && (INCLUDE_ALL_UserController || defined(INCLUDE_AppUserController))
#define AppUserController_

@class AppBaseRestDataConverter;
@class AppBaseRestResult;
@class JavaUtilLoggingLogger;

@interface AppUserController : NSObject {
 @public
  AppBaseRestDataConverter *converter_;
}

+ (JavaUtilLoggingLogger *)logger;

#pragma mark Public

- (instancetype)init;

- (AppBaseRestResult *)sigInWithUserName:(NSString *)username
                                password:(NSString *)password;

@end

J2OBJC_STATIC_INIT(AppUserController)

J2OBJC_FIELD_SETTER(AppUserController, converter_, AppBaseRestDataConverter *)

inline JavaUtilLoggingLogger *AppUserController_get_logger(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilLoggingLogger *AppUserController_logger;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AppUserController, logger, JavaUtilLoggingLogger *)

FOUNDATION_EXPORT void AppUserController_init(AppUserController *self);

FOUNDATION_EXPORT AppUserController *new_AppUserController_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUserController *create_AppUserController_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppUserController)

@compatibility_alias BrComMobilemindAppControllerUserController AppUserController;

#endif

#pragma pop_macro("INCLUDE_ALL_UserController")
