//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/UserRepository.java
//

#ifndef UserRepository_H
#define UserRepository_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "BaseRepository.h"
#include "J2ObjC_header.h"

@class AppUser;
@class ComYahooSquidbSqlProperty;
@class ComYahooSquidbSqlTable;
@class IOSClass;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface AppUserRepository : AppBaseRepository

#pragma mark Public

- (instancetype __nonnull)init;

- (jboolean)exists;

- (id<JavaUtilList>)findAll;

- (AppUser *)findByIdWithLong:(jlong)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)arg0
                withComYahooSquidbSqlTable:(ComYahooSquidbSqlTable *)arg1
        withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)arg2
             withComYahooSquidbSqlProperty:(ComYahooSquidbSqlProperty *)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AppUserRepository)

FOUNDATION_EXPORT void AppUserRepository_init(AppUserRepository *self);

FOUNDATION_EXPORT AppUserRepository *new_AppUserRepository_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppUserRepository *create_AppUserRepository_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppUserRepository)

@compatibility_alias BrComMobilemindAppRepositoryUserRepository AppUserRepository;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // UserRepository_H
