//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ValidatorUtil.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ValidatorUtil")
#ifdef RESTRICT_ValidatorUtil
#define INCLUDE_ALL_ValidatorUtil 0
#else
#define INCLUDE_ALL_ValidatorUtil 1
#endif
#undef RESTRICT_ValidatorUtil

#if !defined (AppBaseValidatorUtil_) && (INCLUDE_ALL_ValidatorUtil || defined(INCLUDE_AppBaseValidatorUtil))
#define AppBaseValidatorUtil_

@interface AppBaseValidatorUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)isValidCNPJWithNSString:(NSString *)cnpj;

+ (jboolean)isValidCPFWithNSString:(NSString *)cpf;

+ (jboolean)isValidEmailWithNSString:(NSString *)email;

@end

J2OBJC_STATIC_INIT(AppBaseValidatorUtil)

FOUNDATION_EXPORT void AppBaseValidatorUtil_init(AppBaseValidatorUtil *self);

FOUNDATION_EXPORT AppBaseValidatorUtil *new_AppBaseValidatorUtil_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseValidatorUtil *create_AppBaseValidatorUtil_init(void);

FOUNDATION_EXPORT jboolean AppBaseValidatorUtil_isValidCPFWithNSString_(NSString *cpf);

FOUNDATION_EXPORT jboolean AppBaseValidatorUtil_isValidCNPJWithNSString_(NSString *cnpj);

FOUNDATION_EXPORT jboolean AppBaseValidatorUtil_isValidEmailWithNSString_(NSString *email);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseValidatorUtil)

@compatibility_alias BrComMobilemindJ2objcUtilValidatorUtil AppBaseValidatorUtil;

#endif

#pragma pop_macro("INCLUDE_ALL_ValidatorUtil")
