//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/VelosterModel.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_VelosterModel")
#ifdef RESTRICT_VelosterModel
#define INCLUDE_ALL_VelosterModel 0
#else
#define INCLUDE_ALL_VelosterModel 1
#endif
#undef RESTRICT_VelosterModel

#if !defined (AppBaseVelosterModel_) && (INCLUDE_ALL_VelosterModel || defined(INCLUDE_AppBaseVelosterModel))
#define AppBaseVelosterModel_

@interface AppBaseVelosterModel : NSObject

#pragma mark Public

- (instancetype)init;

- (jint)getId;

- (jint)getServerId;

- (NSString *)getSyncStatus;

- (jboolean)isPersited;

- (jboolean)isSyncChanged;

- (jboolean)isSyncDeleted;

- (jboolean)isWebPersisted;

- (void)setIdWithInt:(jint)serverId;

- (void)setServerIdWithInt:(jint)serverId;

- (void)setSyncStatusWithNSString:(NSString *)status;

- (AppBaseVelosterModel *)toSyncChange;

- (AppBaseVelosterModel *)toSyncOk;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseVelosterModel)

FOUNDATION_EXPORT void AppBaseVelosterModel_init(AppBaseVelosterModel *self);

FOUNDATION_EXPORT AppBaseVelosterModel *new_AppBaseVelosterModel_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseVelosterModel *create_AppBaseVelosterModel_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseVelosterModel)

@compatibility_alias BrComMobilemindJ2objcModelVelosterModel AppBaseVelosterModel;

#endif

#pragma pop_macro("INCLUDE_ALL_VelosterModel")
